### ISSUE TITLE
Improvement: checking permissions before doing a manual backup

### ISSUE THREAD

**Issue by sjolicoeur** [pivotal-cf/service-backup#3]
if I am logged in as the wrong user I expect to be told I am not allow to perform the backup.
if I am logged in as root I expect the manual-backup to drop privileges and perform the backup as the user specified in the config yaml.

**Comment by addytripathi** [comment]
Hey @sjolicoeur .. we're not making changes to the Service Backups product at the moment, we've had this discussion with @jzlwang . MySQL can PR this change if this is a priority for you. CC: @winnab

**Comment by addytripathi** [comment]
Closing issue per above comment.
